### ISSUE TITLE
Maximum Upload Size Exceeded in Standalone Version

### ISSUE THREAD

**Issue by davisidarta** [romanhaa/Cerebro#20]
Hey @romanhaa 

First of all: THANK YOU for this amazing tool! I use Cerebro on a everyday basis and my non-bioinformatician colleagues love it for exploring results I share. I'm also sharing Cerebro objects for our new article submissions :) 

I'm opening this issue because of a minor issue when using Cerebro on a Windows machine. Similarly to Cerebro implementation in R, an error message appears when trying to upload large files to Cerebro, stating 'Maximum Upload Size Exceeded'.

When I use Cerebro within R, I can easily bypass this by setting `MaxFileSize` to a larger value. However, I couldn't figure out how to do this when using a Windows standalone version (which I requested to be installed on my lab study room computer). Is there any way to set this value when using Cerebro in the standalone version?

**Comment by romanhaa** [comment]
Hi @davisidarta! It's always great to hear that people find Cerebro useful. That's exactly what I made it for :)

Fixing the issue you describe should be pretty straight-forward. What you need to do is the following: Navigate to the directory where Cerebro is installed, and from there to `resources/app`. In there, you should find a file called `app.R` which contains the call to `cerebroApp::launchCerebro()`. After adding the `maxFileSize` parameter with the proper value you should be ready to load larger files into Cerebro.

Please let me know if this worked for you.

In the future, I'll probably increase the limit or remove it completely, maybe just add a warning instead.

**Comment by davisidarta** [comment]
@romanhaa  That solved it! Thank you lots :)

**Comment by rpauly** [comment]
I am having the same issue...so my .rds object is 5.3gb and I changed the maxFileSize to 6gb and it still throws an error.
Below is the app.R edited...is the syntax not right?

##----------------------------------------------------------------------------##
## set .libPaths() to load packages from inside Cerebro standalone version
##----------------------------------------------------------------------------##
if ( grepl(tolower(Sys.info()["sysname"]), pattern = "^win") )
{
  .libPaths(paste0(getwd(), "/R-Portable-Win/library"))
} else if ( grepl(tolower(Sys.info()["sysname"]), pattern = "darwin") )
{
  .libPaths(paste0(getwd(), "/R-Portable-Mac/library"))
}

##----------------------------------------------------------------------------##
## launch Cerebro interface
##----------------------------------------------------------------------------##
cerebroApp::launchCerebro(maxFileSize 6GB)

**Comment by JMarzec** [comment]
Hi @davisidarta 

On top of @romanhaa's hint I also had to change limits on the server where I'm hosting Cerebro. In my case changing the [server's maximum HTTP request size allowance](https://www.keycdn.com/support/413-request-entity-too-large) solved the issue.

Best
Jacek
