### ISSUE TITLE
Input of Monocle trajectory analysis

### ISSUE THREAD

**Issue by phoebee-h** [romanhaa/Cerebro#21]
Hi, 
My name is Phoebe.
Thanks for the nice work, with such a clear demonstration!
I wonder what's the input in your trajectory step in this [README.md](https://github.com/romanhaa/Cerebro/blob/4b3140ca803745f861d1aceb51a63ad150bcb5c7/examples/pbmc_10k_v3/Seurat_v3/README.md)? To my knowledge, the "`seurat@assays$RNA@data`" stores the normalized UMI count matrix, which might not be recommended to import in the Monocle object as I saw [here](http://cole-trapnell-lab.github.io/monocle-release/docs/#classifying-and-counting-cells):
 
![image](https://user-images.githubusercontent.com/28743573/76725622-bc90ad00-6789-11ea-975e-e7e9fbb78be4.png)

I supposed "`seurat@assays$RNA@counts`" would be the suggested one as mentioned above? 

Any suggestions would be appreciated. Not sure whether I get it wrong or not.
Thank you in advance!

Phoebe

**Comment by romanhaa** [comment]
Hey Phoebe!

Yes you're right, thank you for pointing that out. I must've missed that and will correct the documentation. Even though it's not really clear to me in which step Monocle performs any normalisation. On the other hand, the Trapnell group advocates using Monocle 3 anyway. I hope I find the time to implement support for results from Monocle 3 at some point.

Best,
Roman

**Comment by phoebee-h** [comment]
Thank you, Roman! :)
