### ISSUE TITLE
Loading in multiple seurat object

### ISSUE THREAD

**Issue by f0ng1203** [romanhaa/Cerebro#25]
Hi,

Thanks for the great app. I find it very useful to use your app. However, currently I am facing some issues with loading in files.

Based on your example, you load in 4 different H5 files which were produced by 10X Cell Ranger.

For me, I have a hashtag data. I proceeded to demultiplex it and currently I have one big seurat object with all the identifiers. I proceeded to break it down into 5 individual seurat objects (I have 5 groups) and I am lost here. I don't know how to load it into CerebroApp. 

Could you offer some advice?

Thank you very much.

regards,
Fong

**Comment by romanhaa** [comment]
Hi Fong,

I apologize for the long wait before replying. What you'll have to do is export the Seurat objects into a format that is compatible with Cerebro. You can find an example workflow here: https://romanhaa.github.io/cerebroApp/articles/cerebroApp_workflow.html

I hope that helps!

Best,
Roman

**Comment by f0ng1203** [comment]
Roman,

Thanks. I have managed to make it work.

Regards,
Fong

**Comment by romanhaa** [comment]
Great!
